//transaction

export const DEPOSIT_AMOUNT = 'DEPOSIT_AMOUNT';
export const SUCCESS_DEPOSIT_AMOUNT = 'SUCCESS_DEPOSIT_AMOUNT';
export const FAILED_DEPOSIT_AMOUNT = 'FAILED_DEPOSIT_AMOUNT';
export const WITHDRAW_AMOUNT = 'WITHDRAW_AMOUNT';
export const SUCCESS_WITHDRAW_AMOUNT = 'SUCCESS_WITHDRAW_AMOUNT';
export const FAILED_WITHDRAW_AMOUNT = 'FAILED_WITHDRAW_AMOUNT';
export const BANK_STATEMENT = 'BANK_STATEMENT';
export const SUCCESS_BANK_STATEMENT = 'SUCCESS_BANK_STATEMENT';
export const FAILED_BANK_STATEMENT = 'FAILED_BANK_STATEMENT';
